'use strict';
angular.module('app').config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
	$stateProvider.state('main',{
		url:'/main',
		templateUrl:'view/main.html',
		controller:'mainCtrl'
	}).state('position',{ 
		url:'/position/:id',
		templateUrl:'view/template/position.html',
		controller:'positionCtrl'
	}).state('search',{ 
		url:'/search',
		templateUrl:'view/search.html',
		controller:'searchCtrl'
	}).state('myInfo',{ 
		url:'/myInfo',
		templateUrl:'view/myInfo.html',
		controller:'myCtrl'
	}).state('login',{ 
		url:'/login',
		templateUrl:'view/template/login.html',
		controller:'loginCtrl'
	}).state('registerPersonal',{ 
		url:'/registerPersonal',
		templateUrl:'view/template/registerPersonal.html',
		controller:'registerPCtrl'
	}).state('registerCompany',{ 
		url:'/registerCompany',
		templateUrl:'view/template/registerCompany.html',
		controller:'registerCCtrl'
	}).state('mySend',{ 
		url:'/mySend',
		templateUrl:'view/template/mySend.html',
		controller:'mySendCtrl'
	}).state('mySave',{ 
		url:'/mySave',
		templateUrl:'view/template/mySave.html',
		controller:'mySaveCtrl'
	}).state('myPublish',{ 
		url:'/myPublish',
		templateUrl:'view/template/myPublish.html',
		controller:'myPublishCtrl'
	}).state('myResumes',{ 
		url:'/myResumes',
		templateUrl:'view/template/myResumes.html',
		controller:'myResumesCtrl'
	});
	$urlRouterProvider.otherwise('main');	
}])